=== bcgov/business-transparency-registry/btr-api/src/btr_api/schemas/btr-bods/btr-filing.json
{
  "$id": "https://btr.gov.bc.ca/.well_known/schemas/btr-filing.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Significant Individual Filing",
  "description": "This is object describing significant individual filing.",
  "type": "object",
  "properties": {
    "businessIdentifier": {
      "type": "string"
    },
    "noSignificantIndividualsExist": {
      "type": "boolean"
    },
    "effectiveDate": {
      "type": "string",
      "format": "date"
    },
    "entityStatement": {
      "$ref": "https://btr.gov.bc.ca/.well_known/schemas/entity-statement.json"
    },
    "personStatements": {
      "title": "Person statements",
      "description": "An array of natural persons that have control or ownership in filing for the entity.",
      "type": "array",
      "items": {
        "$ref": "https://btr.gov.bc.ca/.well_known/schemas/person-statement.json"
      }
    },
    "ownershipOrControlStatements": {
      "title": "Ownership or Control statements",
      "description": "An array of ownership or control statements in this filing.",
      "type": "array",
      "items": {
        "$ref": "https://btr.gov.bc.ca/.well_known/schemas/ownership-or-control-statement.json"
      }
    }
  },
  "required": [
    "businessIdentifier",
    "effectiveDate",
    "noSignificantIndividualsExist",
    "entityStatement",
    "personStatements",
    "ownershipOrControlStatements"
  ],
  "oneOf": [
    {
      "properties": {
        "noSignificantIndividualsExist": {
          "const": true
        },
        "personStatements": {
          "maxItems": 0
        },
        "ownershipOrControlStatements": {
          "maxItems": 0
        }
      },
      "required": [
        "businessIdentifier",
        "effectiveDate",
        "noSignificantIndividualsExist",
        "entityStatement",
        "personStatements",
        "ownershipOrControlStatements"
      ]
    },
    {
      "properties": {
        "noSignificantIndividualsExist": {
          "const": false
        },
        "personStatements": {
          "minItems": 1
        },
        "ownershipOrControlStatements": {
          "minItems": 1
        }
      }
    }
  ]
}

=== bcgov/business-transparency-registry/btr-web/btr-main-app/utils/123.json
{
  "effectiveDate": "2024-05-02",
  "entityStatement": {
    "name": "0871427 B.C. LTD.",
    "source": {
      "type": [
        "officialRegister",
        "verified"
      ],
      "assertedBy": [
        {
          "uri": "https://www.bcregistry.gov.bc.ca/",
          "name": "BCROS - BC Registries and Online Services"
        }
      ],
      "retrievedAt": "2024-05-03T22:43:33.217Z"
    },
    "entityType": "legalEntity",
    "identifiers": [],
    "isComponent": false,
    "statementID": "72100184-5569-4d2c-bf8f-c04e9fc5ba5e",
    "statementDate": "2024-05-03",
    "statementType": "entityStatement",
    "publicationDetails": {
      "publisher": {
        "url": "https://www.bcregistry.gov.bc.ca/",
        "name": "BCROS - BC Registries and Online Services"
      },
      "bodsVersion": "0.3",
      "publicationDate": "2024-05-03"
    }
  },
  "personStatements": [
    {
      "email": "test.test123@test.com",
      "names": [
        {
          "type": "individual",
          "fullName": "BCREG2 Ayisha FIFTY"
        }
      ],
      "source": {
        "type": [
          "selfDeclaration"
        ],
        "assertedBy": [
          {
            "name": "tester33 testing"
          }
        ],
        "description": "Using Gov BC - BTR - Web UI"
      },
      "addresses": [
        {
          "city": "Vancouver",
          "region": "BC",
          "street": "403-1265 Barclay St",
          "country": "CA",
          "postalCode": "V6E 1H5",
          "countryName": "Canada",
          "streetAdditional": "",
          "locationDescription": ""
        }
      ],
      "birthDate": "2024-04-04",
      "personType": "knownPerson",
      "identifiers": [],
      "isComponent": false,
      "statementID": "ca64df7a-1dbe-435a-8a92-fe09cf3cdae1",
      "hasTaxNumber": false,
      "nationalities": [],
      "statementDate": "2024-05-02",
      "statementType": "personStatement",
      "taxResidencies": [
        {
          "code": "CA",
          "name": "Canada"
        }
      ],
      "placeOfResidence": {
        "city": "Vancouver",
        "region": "BC",
        "street": "403-1265 Barclay St",
        "country": "CA",
        "postalCode": "V6E 1H5",
        "countryName": "Canada",
        "streetAdditional": "",
        "locationDescription": ""
      },
      "missingInfoReason": "",
      "publicationDetails": {
        "publisher": {
          "url": "https://www.bcregistry.gov.bc.ca/",
          "name": "BCROS - BC Registries and Online Services"
        },
        "bodsVersion": "0.3",
        "publicationDate": "2024-05-03"
      },
      "isPermanentResidentCa": false
    },
    {
      "email": "test.test123@test.com",
      "names": [
        {
          "type": "individual",
          "fullName": "testera"
        }
      ],
      "source": {
        "type": [
          "selfDeclaration"
        ],
        "assertedBy": [
          {
            "name": "tester33 testing"
          }
        ],
        "description": "Using Gov BC - BTR - Web UI"
      },
      "addresses": [
        {
          "city": "Markham",
          "region": "ON",
          "street": "213-60 Centurian Dr",
          "country": "CA",
          "postalCode": "L3R 8T5",
          "countryName": "Canada",
          "streetAdditional": "",
          "locationDescription": ""
        }
      ],
      "birthDate": "2024-04-03",
      "personType": "knownPerson",
      "identifiers": [],
      "isComponent": false,
      "statementID": "dd050912-77ea-46f9-b3d0-db907f2eab5f",
      "hasTaxNumber": false,
      "nationalities": [],
      "statementDate": "2024-05-02",
      "statementType": "personStatement",
      "taxResidencies": [],
      "placeOfResidence": {
        "city": "Markham",
        "region": "ON",
        "street": "213-60 Centurian Dr",
        "country": "CA",
        "postalCode": "L3R 8T5",
        "countryName": "Canada",
        "streetAdditional": "",
        "locationDescription": ""
      },
      "missingInfoReason": "",
      "publicationDetails": {
        "publisher": {
          "url": "https://www.bcregistry.gov.bc.ca/",
          "name": "BCROS - BC Registries and Online Services"
        },
        "bodsVersion": "0.3",
        "publicationDate": "2024-05-03"
      },
      "isPermanentResidentCa": false
    },
    {
      "email": "email@test.com",
      "names": [
        {
          "type": "individual",
          "fullName": "tester33 testing"
        },
        {
          "type": "alternative",
          "fullName": "wam"
        }
      ],
      "source": {
        "type": [
          "selfDeclaration"
        ],
        "assertedBy": [
          {
            "name": "tester33 testing"
          }
        ],
        "description": "Using Gov BC - BTR - Web UI"
      },
      "addresses": [
        {
          "city": "Saskatoon",
          "region": "SK",
          "street": "123-655 Kenderdine Rd",
          "country": "CA",
          "postalCode": "S7N 4W9",
          "countryName": "Canada",
          "streetAdditional": "street additional",
          "locationDescription": "la la la"
        }
      ],
      "birthDate": "2018-02-01",
      "personType": "knownPerson",
      "identifiers": [
        {
          "id": "402 931 299",
          "scheme": "CAN-TAXID",
          "schemeName": "ITN"
        }
      ],
      "isComponent": false,
      "statementID": "227c6cdc-0fcc-4794-b5fa-af65cf58e5ec",
      "hasTaxNumber": true,
      "nationalities": [
        {
          "code": "CA",
          "name": "Canada"
        }
      ],
      "statementDate": "2024-02-01",
      "statementType": "personStatement",
      "taxResidencies": [
        {
          "code": "CA",
          "name": "Canada"
        }
      ],
      "placeOfResidence": {
        "city": "Saskatoon",
        "region": "SK",
        "street": "123-655 Kenderdine Rd",
        "country": "CA",
        "postalCode": "S7N 4W9",
        "countryName": "Canada",
        "streetAdditional": "street additional",
        "locationDescription": "la la la"
      },
      "missingInfoReason": "",
      "publicationDetails": {
        "publisher": {
          "url": "https://www.bcregistry.gov.bc.ca/",
          "name": "BCROS - BC Registries and Online Services"
        },
        "bodsVersion": "0.3",
        "publicationDate": "2024-05-03"
      },
      "isPermanentResidentCa": false
    }
  ],
  "businessIdentifier": "BC0871427",
  "ownershipOrControlStatements": [
    {
      "source": {
        "type": [
          "selfDeclaration"
        ],
        "assertedBy": [
          {
            "name": "tester33 testing"
          }
        ],
        "description": "Using Gov BC - BTR - Web UI"
      },
      "subject": {
        "describedByEntityStatement": ""
      },
      "interests": [],
      "isComponent": false,
      "statementID": "7dcd8dda-271d-4cdd-b873-379df12d0d77",
      "statementDate": "2024-05-02",
      "statementType": "ownershipOrControlStatement",
      "interestedParty": {
        "describedByPersonStatement": "ca64df7a-1dbe-435a-8a92-fe09cf3cdae1"
      },
      "publicationDetails": {
        "publisher": {
          "url": "https://www.bcregistry.gov.bc.ca/",
          "name": "BCROS - BC Registries and Online Services"
        },
        "bodsVersion": "0.3",
        "publicationDate": "2024-05-03"
      }
    },
    {
      "source": {
        "type": [
          "selfDeclaration"
        ],
        "assertedBy": [
          {
            "name": "tester33 testing"
          }
        ],
        "description": "Using Gov BC - BTR - Web UI"
      },
      "subject": {
        "describedByEntityStatement": ""
      },
      "interests": [],
      "isComponent": false,
      "statementID": "32493608-4e12-4d7f-8655-1de0f2c800f3",
      "statementDate": "2024-05-02",
      "statementType": "ownershipOrControlStatement",
      "interestedParty": {
        "describedByPersonStatement": "dd050912-77ea-46f9-b3d0-db907f2eab5f"
      },
      "publicationDetails": {
        "publisher": {
          "url": "https://www.bcregistry.gov.bc.ca/",
          "name": "BCROS - BC Registries and Online Services"
        },
        "bodsVersion": "0.3",
        "publicationDate": "2024-05-03"
      }
    },
    {
      "source": {
        "type": [
          "selfDeclaration"
        ],
        "assertedBy": [
          {
            "name": "tester33 testing"
          }
        ],
        "description": "Using Gov BC - BTR - Web UI"
      },
      "subject": {
        "describedByEntityStatement": ""
      },
      "interests": [],
      "isComponent": false,
      "statementID": "a4abd2f1-89aa-426f-bcb0-cd4272d2f928",
      "statementDate": "2024-02-01",
      "statementType": "ownershipOrControlStatement",
      "interestedParty": {
        "describedByPersonStatement": "227c6cdc-0fcc-4794-b5fa-af65cf58e5ec"
      },
      "publicationDetails": {
        "publisher": {
          "url": "https://www.bcregistry.gov.bc.ca/",
          "name": "BCROS - BC Registries and Online Services"
        },
        "bodsVersion": "0.3",
        "publicationDate": "2024-05-03"
      }
    }
  ],
  "noSignificantIndividualsExist": false
}
